image: jhipster/jhipster:v6.10.5

cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
        - .maven/
stages:
    - check
    - build
    - test
    - analyze
    - package
    - release
    - deploy
before_script:
    - export NG_CLI_ANALYTICS="false"
    - export MAVEN_USER_HOME=`pwd`/.maven

nohttp:
    stage: check
    script:
        - ./mvnw -ntp checkstyle:check -Dmaven.repo.local=$MAVEN_USER_HOME

maven-compile:
    stage: build
    script:
        - ./mvnw -ntp compile -P-webpack -Dmaven.repo.local=$MAVEN_USER_HOME
    artifacts:
        paths:
            - target/classes/
            - target/generated-sources/
        expire_in: 1 day

maven-test:
    # DinD service is required for Testcontainers
    services:
        - docker:dind

    variables:
        # Instruct Testcontainers to use the daemon of DinD.
        DOCKER_HOST: 'tcp://docker:2375'
        # Improve performance with overlayfs.
        DOCKER_DRIVER: overlay2

    stage: test
    script:
        - ./mvnw -ntp verify -P-webpack -Dmaven.repo.local=$MAVEN_USER_HOME -Dspring.profiles.active=testcontainers
    artifacts:
        reports:
            junit: target/test-results/**/TEST-*.xml
        paths:
            - target/test-results
            - target/jacoco
        expire_in: 1 day


maven-package:
    stage: package
    script:
        - ./mvnw -ntp verify -Pprod -DskipTests -Dmaven.repo.local=$MAVEN_USER_HOME
    artifacts:
        paths:
            - target/*.jar
            - target/classes
        expire_in: 1 day

# Uncomment the following line to use gitlabs container registry. You need to adapt the REGISTRY_URL in case you are not using gitlab.com
#docker-push:
#    stage: release
#    variables:
#        REGISTRY_URL: registry.gitlab.com
#        IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
#    dependencies:
#        - maven-package
#    script:
#        - ./mvnw -ntp compile jib:build -Pprod -Djib.to.image=$IMAGE_TAG -Djib.to.auth.username=gitlab-ci-token  -Djib.to.auth.password=$CI_BUILD_TOKEN -Dmaven.repo.local=$MAVEN_USER_HOME

